version: "3.8"

services:
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - app-network

  # (Optional) If you want a separate Nginx for backend API only
  # nginx-backend:
  #   image: nginx:latest
  #   container_name: ap-backend-nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - backend-prod
  #   networks:
  #     - app-network

networks:
  app-network:
    external: true