version: '3.8'

services:
  # Development service
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
    command: npm run dev
    networks:
      - app-network

  # Production service
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  # Nginx service
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend-prod
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  mongodb_data: